sonar.projectKey=aurify-backend_Aurify-Investment
sonar.organization=aurify-backend
sonar.projectName=Aurify-Investment
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/coverage/**,**/generated/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.test.inclusions=src/**/__tests__/**/*.test.js